os: linux
sudo: required
dist: trusty
sudo: true
language: cpp
compiler: g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
before_install:
    - sudo apt-get update
    - sudo apt install curl
script:
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - export CC=gcc-7 ;
    - export CXX=g++-7 ;
    - g++ --version
    - g++-7 --version
    ./test.sh
