os: linux
dist: trusty
sudo: true
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
before_install:
    - sudo apt-get update
    - sudo apt install curl
script:
    - export CC=gcc-7 ;
    - export CXX=g++-7 ;
    - g++ --version
    - ./test.sh
