os: linux
sudo: required
dist: trusty
sudo: true
language: cpp
compiler: g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
before_install:
    - sudo apt-get update > /dev/null
    - sudo apt install curl
install:
    - sudo apt install -qq g++-7
    - export CC=gcc-7 ;
    - export CXX=g++-7 ;
script:
    - g++ --version
    - ./test.sh
